name: release
on:
  workflow_dispatch: { }
  push:
    branches: [ main ]
    tags: [ '*' ]
    paths:
      - 'app/**'
      - '.github/workflows/release.yaml'
defaults: { run: { shell: bash } }
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
permissions:
  packages: write
  id-token: write
  contents: write
  attestations: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache-dependency-path: app/go.sum
          go-version-file: app/go.mod
      - uses: ko-build/setup-ko@v0.6
        with:
          version: v0.16.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TMP_TOKEN }}
      - run: make publish
        working-directory: app
#        env:
#          GIT_TAG: ${{ github.ref_name }}
